# ~/allsafe-access/allsafe-proxy.yaml
listen_address: "Ipaddress:8080"
cert_file: "/etc/allsafe-proxy/certs/proxy.crt"
key_file: "/etc/allsafe-proxy/certs/proxy.key"
ca_cert_file: "/etc/allsafe-proxy/certs/proxy_ca.crt"
agent_listen_port: 8081
agent_heartbeat_timeout_minutes: 5

# Application secrets - All of these must be changed from their default values.
secret_key: "a-very-long-and-secure-secret-key-for-signing-tokens" # <<< Add this
admin_token: "a-very-secret-admin-token-for-proxy-communication" # <<< Add this
registration_token: "mySecureSharedToken" # <<< This should be a strong, unique token